# Generated by Django 4.1.1 on 2022-10-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfevents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Soundsystem_rank',
        ),
        migrations.RemoveField(
            model_name='event',
            name='instrumentals_rank',
        ),
        migrations.RemoveField(
            model_name='event',
            name='selectas_rank',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vocals_rank',
        ),
    ]
