# Generated by Django 4.1.1 on 2022-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfevents', '0002_remove_event_soundsystem_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Plan', 'Planning'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Plan', max_length=20, verbose_name='Status'),
        ),
    ]
