# Generated by Django 4.1.1 on 2023-01-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfevents', '0004_alter_eventenquiry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventenquiry',
            name='phone',
        ),
    ]
