# Generated by Django 4.1.1 on 2022-10-11 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Artist Name')),
                ('rank', models.IntegerField(verbose_name='rank: Headline is low number')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artist Location')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Artist Email')),
                ('artist_url', models.URLField(blank=True, null=True, verbose_name='Artist Website')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Artist Type Name')),
                ('selecta', models.BooleanField(default=False, verbose_name='Selecta (DJ, CDJ etc.) = true')),
                ('vocalist', models.BooleanField(default=False, verbose_name='Vocalist (MC; Singer; Beatbox etc.) = true')),
                ('instrumentalist', models.BooleanField(default=False, verbose_name='Instrumentist (including electronic) = True')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Musical Genre Name')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Label Name')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Label location')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label contact')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Label phone number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Label email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Label web address')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Producer Name')),
                ('producer_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producer Location')),
                ('Producer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Producer Email')),
                ('Producer_url', models.URLField(blank=True, null=True, verbose_name='Producer Website')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('label', models.ManyToManyField(related_name='Producer_labels', to='music.label')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Studio Name')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Studio location')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Studiol contact')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Studio phone number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Studio email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Studio web address')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Track Name')),
                ('recorded_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Track Recorded Date')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Track Release Date')),
                ('track_url', models.URLField(blank=True, null=True, verbose_name='Track webaddress')),
                ('track_embed', models.CharField(blank=True, max_length=500, null=True, verbose_name='Embed Track html')),
                ('track_info', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('featured_artists', models.ManyToManyField(related_name='track_artists', to='music.artist')),
                ('genre', models.ManyToManyField(related_name='track_genre', to='music.genre')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.label')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.producer')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Soundsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Sound Name')),
                ('rank', models.IntegerField(verbose_name='Sound rank')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact phone number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('sound_url', models.URLField(blank=True, null=True, verbose_name='weblink')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('genre', models.ManyToManyField(related_name='sound_genre', to='music.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Mix Name')),
                ('recorded_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Mix Recorded Date')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Mix Release Date')),
                ('mix_url', models.URLField(blank=True, null=True, verbose_name='Mix weblink')),
                ('mix_embed', models.CharField(blank=True, max_length=500, null=True, verbose_name='Embed mix html')),
                ('mix_info', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_dj', to='music.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_artists', to='music.artist')),
                ('genre', models.ManyToManyField(related_name='mix_genre', to='music.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Sound Name')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact phone number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('sound_url', models.URLField(blank=True, null=True, verbose_name='weblink')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('genre', models.ManyToManyField(related_name='group_genre', to='music.genre')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_type',
            field=models.ManyToManyField(related_name='artist_type', to='music.artisttype'),
        ),
        migrations.AddField(
            model_name='artist',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.soundsystem'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(related_name='artist_genre', to='music.genre'),
        ),
    ]
