# Generated by Django 4.1.1 on 2022-10-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['rank']},
        ),
    ]
