# Generated by Django 4.1.1 on 2023-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_artist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Studio contact'),
        ),
    ]
