# Generated by Django 4.1.1 on 2022-10-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mfevents', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_bol', models.BooleanField(default=False, verbose_name='Event True/False')),
                ('mix_bol', models.BooleanField(default=False, verbose_name='Mix True/False')),
                ('track_bol', models.BooleanField(default=False, verbose_name='Track True/False')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Entrydate')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('edited_dt', models.DateTimeField(auto_now=True, verbose_name='Date edited')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfevents.event')),
                ('mix', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.mix')),
                ('track', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
        ),
    ]
