# Generated by Django 4.1.1 on 2022-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_infohome_links_photohome'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='logo_lnk',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='Link Logo'),
        ),
        migrations.AddField(
            model_name='links',
            name='name',
            field=models.CharField(default='name', max_length=100, verbose_name='Link name'),
        ),
        migrations.AddField(
            model_name='links',
            name='type_lnk',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Type'),
        ),
    ]
