# Generated by Django 4.1.1 on 2022-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_links_logo_lnk_links_name_links_type_lnk'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='mflink',
            field=models.BooleanField(default=False, verbose_name='More Fire link'),
        ),
        migrations.AlterField(
            model_name='links',
            name='link_url',
            field=models.URLField(verbose_name='Link url'),
        ),
        migrations.AlterField(
            model_name='links',
            name='type_lnk',
            field=models.CharField(choices=[('fb', 'Facebook'), ('twit', 'Twitter'), ('inst', 'Instagram'), ('other', 'Other')], default='Other', max_length=20, verbose_name='Type'),
        ),
    ]
