# Generated by Django 4.1.1 on 2022-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_links_mflink_alter_links_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='type_lnk',
            field=models.CharField(choices=[('band', 'Bandcamp'), ('mixc', 'MixCloud'), ('fb', 'Facebook'), ('twit', 'Twitter'), ('inst', 'Instagram'), ('other', 'Other')], default='Other', max_length=20, verbose_name='Type'),
        ),
    ]
